# Cargo configuration for hello-gpu
#
# Set the following environment variables to match your local CUDA and MSVC
# installation. They may be defined here or exported in your shell.
#
# CUDA_PATH              - root of the CUDA Toolkit, e.g. C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.5
# CUDA_TOOLKIT_ROOT_DIR  - usually the same as CUDA_PATH
# CUDA_LIBRARY_PATH      - path to the 64-bit CUDA libs, typically ${CUDA_PATH}\\lib\\x64
# CCBIN_PATH             - full path to cl.exe from the Visual Studio Build Tools
#
# Using placeholders keeps the file portable across machines.

[env]
CUDA_PATH = "${CUDA_PATH}"
CUDA_TOOLKIT_ROOT_DIR = "${CUDA_PATH}"
CUDA_LIBRARY_PATH = "${CUDA_PATH}\\lib\\x64"
CCBIN_PATH = "${CCBIN_PATH}"

[target.'cfg(windows)']
rustflags = [
    "-C", "link-arg=/LIBPATH:${CUDA_LIBRARY_PATH}",
    "-C", "link-arg=cudart.lib",
    "-C", "link-arg=cuda.lib",
    "-C", "link-arg=cudadevrt.lib",
]
