[target.'cfg(windows)']
rustflags = [
    "-C", "link-arg=/LIBPATH:C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.5\\lib\\x64",
    "-C", "link-arg=cudart.lib",
    "-C", "link-arg=cuda.lib",
    "-C", "link-arg=cudadevrt.lib",
]

[env]
CUDA_PATH = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.5"
CUDA_TOOLKIT_ROOT_DIR = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.5"
CUDA_LIBRARY_PATH = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.5\\lib\\x64"
CCBIN_PATH = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\Hostx64\\x64\\cl.exe"
